# omnisharp: 主にUnity用
## 上手く動いていないので一旦なしで

## 本体
# [[plugins]]
# repo = 'OmniSharp/omnisharp-vim'
# on_ft = ['cs']
# hook_add = '''
# let g:OmniSharp_server_stdio = 1
# if has('win32')
#   let g:OmniSharp_translate_cygwin_wsl = 0
# else
#   let g:OmniSharp_translate_cygwin_wsl = 1
# endif
# '''

## deoplete
# [[plugins]]
# repo = 'Robzz/deoplete-omnisharp'
# on_source = ['deoplete.nvim']


# [[plugins]]
# repo = 'OmniSharp/omnisharp-vim'
# on_ft = ['cs']
# hook_add = '''
# let g:OmniSharp_translate_cygwin_wsl = 1
# '''


[[plugins]]
repo = 'voldikss/vim-floaterm'
hook_source = '''
nnoremap <silent><Space>r :FloatermNew --height=0.4 --width=0.7 --position=top fzf<CR>

if has ('win32')
  let g:floaterm_shell = 'powershell'
endif
let g:floaterm_wintype = 'floating'
let g:floaterm_wintitle = ''
let g:floaterm_winblend = 1
let g:floaterm_position = 'bottom'
let g:floaterm_width = 0.6
let g:floaterm_height = 0.3
let g:floaterm_open_command = 'drop'
let g:floaterm_autoclose = 2
let g:floaterm_borderchars = ['', '', '', '', '', '', '', '']
let g:floaterm_keymap_toggle = '<Space>k'

highlight FloatermBorder guibg=#005F87 guifg=white
set winblend=20
'''
on_event = 'VimEnter'
