# omnisharp: 主にUnity用
## 上手く動いていないので一旦なしで

## 本体
# [[plugins]]
# repo = 'OmniSharp/omnisharp-vim'
# on_ft = ['cs']
# hook_add = '''
# let g:OmniSharp_server_stdio = 1
# if has('win32')
#   let g:OmniSharp_translate_cygwin_wsl = 0
# else
#   let g:OmniSharp_translate_cygwin_wsl = 1
# endif
# '''

## deoplete
# [[plugins]]
# repo = 'Robzz/deoplete-omnisharp'
# on_source = ['deoplete.nvim']


# [[plugins]]
# repo = 'OmniSharp/omnisharp-vim'
# on_ft = ['cs']
# hook_add = '''
# let g:OmniSharp_translate_cygwin_wsl = 1
# '''


[[plugins]]
repo = 'voldikss/vim-floaterm'
hook_source = '''
tnoremap <silent><Space>k <C-\><C-n>:FloatermToggle<CR>
nnoremap <silent><Space>k :FloatermToggle<CR>

let g:floaterm_winblend = 1
let g:floaterm_position = 'bottom'
let g:floaterm_width = 0.6
let g:floaterm_height = 0.3
" let g:floaterm_borderchars = ['-', '|', '-', '|', '-', '-', '|', '|']
let g:floaterm_borderchars = ['', '', '', '', '', '', '', '']
highlight FloatermBorder guibg=gray guifg=white
set windblend=20
'''
on_event = 'VimEnter'
