# omnisharp: 主にUnity用
## 上手く動いていないので一旦なしで

## 本体
# [[plugins]]
# repo = 'OmniSharp/omnisharp-vim'
# on_ft = ['cs']
# hook_add = '''
# let g:OmniSharp_server_stdio = 1
# if has('win32')
#   let g:OmniSharp_translate_cygwin_wsl = 0
# else
#   let g:OmniSharp_translate_cygwin_wsl = 1
# endif
# '''

## deoplete
# [[plugins]]
# repo = 'Robzz/deoplete-omnisharp'
# on_source = ['deoplete.nvim']


# [[plugins]]
# repo = 'OmniSharp/omnisharp-vim'
# on_ft = ['cs']
# hook_add = '''
# let g:OmniSharp_translate_cygwin_wsl = 1
# '''
